# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f81b4e7944952fb4c75080ed3ecab54863d2202bd970009f798845b0ba2cffab8f981a9a924e5cebe516da24518201e2adc61bef53c6b6341005b33cab96b8cd

test:
  secret_key_base: 31cbebc5d9c71c3f04b4b9ac9364ee73d522f644783e9dbd6c419b8682aabc2e96bcdcf805f0bfa75f5663f1280fb192f7f5df384006c569e7208e8d1df02536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
